version: '3'

services:
  jekyll:
    image: jekyll/jekyll
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - my-bundle:/usr/local/bundle
    restart: unless-stopped
    command: jekyll serve

volumes:
  my-bundle:
 
